spin_version = "1"
authors = ["Thorsten Hans <thorsten.hans@gmail.com>"]
description = "Redis Consumer in GoLang"
name = "message-consumer-go"
trigger = { type = "redis", address = "redis://localhost:6379" }
version = "0.1.0"

[[component]]
id = "message-consumer-go"
source = "main.wasm"
[component.trigger]
channel = "codetalks"
[component.build]
command = "tinygo build -wasm-abi=generic -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
