spin_version = "1"
authors = ["Thorsten Hans <thorsten.hans@gmail.com>"]
description = "Hello World"
name = "hello-world"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "hello-world"
source = "target/wasm32-wasi/release/hello_world.wasm"
[component.trigger]
route = "/hello"
[component.build]
command = "cargo build --target wasm32-wasi --release"
